MASTER_CHECKLIST = [
("Critical & Insurance Spares Governance","Identify, classify & validate critical and insurance spares with risk matrix"),
("Single Point Failure Analysis","Identify all single point tripping in PLC/Drives/Field"),
("Pain Point Tripping Analysis","Analyze last 1-year tripping data and identify recurring failures"),
("CPU Memory & System Cleanup","Check CPU memory usage, delete temp files in EWS/OWS"),
("Control Philosophy Documentation","Prepare/update control philosophy"),
("PLC & Drive Backup System","Ensure latest backups (online + offline)"),
("Modification Register","Maintain updated logic & P&ID modification records"),
("PLC Logic Validation","Cross-check PLC logic vs commissioning logic"),
("EMG Start/Stop SOP","Prepare emergency operation procedures"),
("Shutdown Interlock Validation","Validate all interlocks during shutdown (>3 days)"),
("Calibration Traceability","Ensure calibration records & traceability"),
("PM Optimization","Review PM, calculate effectiveness & revise plans"),
("CAPA Implementation","RCA + CAPA for all E&I failures"),
("System Health Check","Monitor CPU load, network health & diagnostics"),
("UPS Health & Integration","Verify UPS backup & integrate signals to HMI"),
("Managed Switch Maintenance","Annual cycling + configuration backup"),
("Recurrence Tracking System","Develop failure trend & tracking mechanism"),
("Critical Spare Validation","Validate critical spares with failure data"),
("Obsolete Inventory Identification","List obsolete/unusable items"),
("Aging & Dead Stock Review","Analyze aging stock & action plan"),
("Inventory Norm Validation","Verify min-max levels"),
("Long Lead & High-Cost Items","Identify & ensure stocking strategy"),
("Vendor Duplication Check","Optimize vendor base"),
("Spare Consolidation Plan","Submit consolidated spare plan to C&I"),
("Skill Gap Assessment","Identify skill gaps & training plan")
]

AUDIT_DATABASE = {
    "Power Plant (3x130MW)": MASTER_CHECKLIST,
    "Power Plant (116MW)": MASTER_CHECKLIST,
    "Pellet Plant": MASTER_CHECKLIST,
    "Beneficiation": MASTER_CHECKLIST,
    "Sinter": MASTER_CHECKLIST,
    "RMHS": MASTER_CHECKLIST,
    "SMS-1": MASTER_CHECKLIST,
    "SMS-2": MASTER_CHECKLIST,
    "Coke Oven": MASTER_CHECKLIST,
    "Oxygen Plant": MASTER_CHECKLIST,
    "CRM": MASTER_CHECKLIST,
    "WRM": MASTER_CHECKLIST,
    "CSP Caster": MASTER_CHECKLIST,
    "Blast Furnace": MASTER_CHECKLIST,
    "LCP": MASTER_CHECKLIST,
    "DRI": MASTER_CHECKLIST,
    "CRM Kolkata": MASTER_CHECKLIST,
    "CRM Chandigarh": MASTER_CHECKLIST,
}